config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'home#index'
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :categories, only: [:show]
  root to: 'static_pages#top'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  enum role: { general: 0, viewer: 1, admin: 2 }

  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  before_action :admin?

  layout 'admin/application'

  private
    def admin?
      unless current_user && current_user.role == "admin"
        render 'error/404', status: :not_found
      end
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = 'Category was successfuly created.'
      redirect_to admin_categories_url
    else
      flash.now[:alert] = 'Invalid values'
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category was successfuly updated.'
      redirect_to admin_categories_url
    else
      flash.now[:alert] = 'Invalid values'
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = 'Category was successfuly deleted.'
      redirect_to admin_categories_url
    else
      flash.now[:alert] = 'Destroy failed.'
      render :index
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :authenticate_user!
  before_action :set_categories

  def set_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category

  def show
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: []
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: :create
  before_action :reset_session_before_login, only: :create

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    end

  private
    def reset_session_before_login
      user_return_to = session[:user_return_to]
      reset_session

      session[:user_return_to] = user_return_to if user_return_to
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <th scope="row"><%= category.id %></th>
  <td><%= category.name %></td>
  <td><%= link_to 'EDIT', edit_admin_category_path(category), class: 'btn btn-light' %></td>
  <td><%= link_to 'DESTROY', admin_category_path(category), class: 'btn btn-light', method: :delete, data: { confirm: 'Delete?' } %></td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for(category, url: url) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control #{'is-invalid' if @category.errors[:name].any?}" %>
    <% @category.errors[:name].each do |error| %>
      <div class="invalid-feedback">
        <%= "カテゴリ名#{error}" %>
      </div>
    <% end %>
  </div>

  <%= f.submit btn, class: 'btn btn-dark' %>
<% end %>

<hr>

<%= link_to 'BACK', admin_categories_path, class: 'btn btn-dark' %>

app/views/admin/categories/edit.html.erb
<div class="container">
  <h2>Edit category</h2>

  <%= render 'form', category: @category, url: admin_category_path, btn: 'UPDATE' %>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Categories</h1>
    <p>categories</p>
    <%= link_to 'ADD CATEGORY', new_admin_category_path, class: 'btn btn-dark' %>
  </div>

  <table class="table table-hover table-dark table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th scope="col">Category Name</th>
        <th scope="col">Operations</th>
      </tr>
    </thead>
    <tbody>
      <%= render @categories %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
  <h2>New category</h2>

  <%= render 'form', category: @category, url: admin_categories_path, btn: 'CREATE' %>
</div>

app/views/admin/home/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Home</h1>
    <p>home</p>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= @category.name %></h1>
    <p>Find me in app/views/categories/index.html.erb</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <%= link_to 'ATE', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        <% if signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="categoriesNav" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              CATEGORIES
            </a>
            <div class="dropdown-menu" aria-labelledby="categoriesNav">
              <% @categories.each do |category| %>
                <%= link_to category.name, category_path(category), class: 'dropdown-item' %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'SING OUT', destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'SING UP', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'SIGN IN', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'ATE', admin_root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'CATEGORIES', admin_categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'SING OUT', destroy_user_session_path, class: 'nav-link', method: :delete %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ate</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/admin/header' %>
  <% if notice %><div class="alert alert-success text-center mb-0"><%= notice %></div><% end %>
  <% if alert %><div class="alert alert-warning text-center mb-0"><%= alert %></div><% end %>
  <main class="mt-4">
    <%= yield %>
  </main>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ate</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <% if notice %><div class="alert alert-success text-center mb-0"><%= notice %></div><% end %>
  <% if alert %><div class="alert alert-warning text-center mb-0"><%= alert %></div><% end %>
  <main class="mt-4">
    <%= yield %>
  </main>
</body>

</html>

app/views/static_pages/top.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>ATE</h1>
    <p>ATEは、自分が習得したい技術や知識を管理するアプリケーションです。</p>
  </div>
</div>